"""Builds the real, scored dataset the RxContinuity website runs on.

Scores every currently-listed ("Current") shortage with the trained
Phase 1 discontinuation-risk model, attaches plain-English reasons,
and adds a duration context line from the Phase 2 survival analysis.
Writes docs/data/drugs.js - a plain JS file (not JSON fetched over
CORS) so the static site can just <script src> it with no server
needed, including for local file:// preview.

Re-running this script (e.g. on a schedule via GitHub Actions) picks
up whatever the latest data/raw/*.csv snapshot says, so the site's
numbers stay current without hand-editing anything.
"""

import json

import pandas as pd

from shortage_risk import (
    CAT_FEATURES,
    MODEL_FEATURES,
    build_dataset,
    discontinuation_rate_by,
    make_pipeline,
)
from duration_model import build_survival_dataset, km_by_group, median_survival_days


def reason_chips(row, dosage_rates, category_rates):
    chips = []

    n = int(row["suppliers_in_shortage_list"])
    if n <= 2:
        chips.append(f"Only {n} other supplier{'s' if n != 1 else ''} currently listed")
    elif n <= 8:
        chips.append(f"{n} other suppliers currently listed")
    else:
        chips.append(f"{n} other suppliers currently listed (well-supplied)")

    dosage = row["dosage_form"]
    if dosage in dosage_rates.index:
        rate = dosage_rates.loc[dosage, "discontinuation_rate"]
        chips.append(f"{dosage} dosage form ({rate:.0%} historical discontinuation rate)")
    else:
        chips.append(f"{dosage} dosage form")

    cat = row["therapeutic_category"]
    if cat in category_rates.index:
        rate = category_rates.loc[cat, "discontinuation_rate"]
        chips.append(f"{cat} category ({rate:.0%} historical discontinuation rate)")
    else:
        chips.append(f"{cat} category")

    return chips


def duration_context(row, km_by_tier):
    n = row["suppliers_in_shortage_list"]
    tier = "1-2 (concentrated)" if n <= 2 else ("3-8 (moderate)" if n <= 8 else "9+ (many suppliers)")
    km = km_by_tier.get(tier)
    if km is None:
        return None
    med = median_survival_days(km)
    if med is not None:
        return f"Shortages with this level of supplier concentration typically reach a final determination within ~{med:.0f} days."
    return "Shortages with this level of supplier concentration typically stay open, undecided, for years rather than resolving quickly."


def build():
    df = build_dataset()
    pipe = make_pipeline("gbm")
    pipe.fit(df[MODEL_FEATURES], df["is_discontinuation"])

    dosage_rates = discontinuation_rate_by(df, "dosage_form", min_rows=10)
    category_rates = discontinuation_rate_by(df, "therapeutic_category", min_rows=10)

    sdf = build_survival_dataset()
    fits, _ = km_by_group(sdf, "supplier_tier", min_group_size=30)

    current = df[df["status"] == "Current"].copy()
    proba = pipe.predict_proba(current[MODEL_FEATURES])[:, 1]
    current["risk_score"] = (proba * 100).round().astype(int)

    records = []
    for _, row in current.iterrows():
        records.append({
            "generic_name": row["generic_name"],
            "brand_name": row["brand_name"] if isinstance(row["brand_name"], str) else None,
            "route": row["route"],
            "dosage_form": row["dosage_form"],
            "therapeutic_category": row["therapeutic_category"],
            "suppliers_in_shortage_list": int(row["suppliers_in_shortage_list"]),
            "risk_score": int(row["risk_score"]),
            "reasons": reason_chips(row, dosage_rates, category_rates),
            "duration_context": duration_context(row, fits),
        })

    # de-duplicate by generic_name, keeping the highest-risk record (a
    # generic name can have multiple manufacturer/package rows)
    by_name = {}
    for r in records:
        key = r["generic_name"]
        if key not in by_name or r["risk_score"] > by_name[key]["risk_score"]:
            by_name[key] = r
    records = sorted(by_name.values(), key=lambda r: (-r["risk_score"], r["generic_name"]))

    return records


if __name__ == "__main__":
    import os
    from datetime import date
    records = build()
    os.makedirs("docs/data", exist_ok=True)
    with open("docs/data/drugs.js", "w") as f:
        f.write("// Auto-generated by src/build_site_data.py - do not hand-edit\n")
        f.write("window.RX_DRUGS = ")
        json.dump(records, f, indent=1)
        f.write(";\n")
        f.write('window.RX_DATA_BUILT_AT = "' + date.today().isoformat() + '";\n')
    print(f"wrote docs/data/drugs.js: {len(records)} drugs")
    print(f"risk score range: {min(r['risk_score'] for r in records)} - {max(r['risk_score'] for r in records)}")
